#Note: Any modification of this file required a restart of Apache Server
#This file must be remove from orchestrator web application root folder and
#placed within /etc/orchestrator/orchestrator-client.conf !

#Information related to the client login. Required by the fusiondirectory-orchestrator-client.
ORCHESTRATOR_LOGIN="orchestrator"
ORCHESTRATOR_PASSWORD="tester"

#Information related to the FusionDirectory Orchestrator Endpoint used by the client
ORCHESTRATOR_API_URL="http://fd.fusiondirectory.org/orchestrator"
